# Lab 7: 

In this lab, we'll explore the effect of salt water intrustion on sea level rise (SLR) for two distinct regions. We'll use real oceanographic data from Ferguson and Gleeson (2012).

## 7.1 - Data Preparation

In [4]:
import pandas as pd
import numpy as np
# Load in our data

data = pd.read_csv('./7_data.csv')
data = data.set_index(['loc'])
display(data)

         H_coast  H_well  distance  depth_b  width  depth_d
loc
Tampa          0       5     10000       50      1       50
Seattle        0     100     10000      250      1      250

In [5]:
# Define our constants

hyd_cond = 1.6e-5 # Hydraulic Conductivity
spec_grav = 1.028 # Specific Gravity of salt water

## 7.2 - Hydrolic Gradient Calculation
We are particularly interested in the impact of sea-level rise (SLR) on these two regions. An important piece of this analysis is examining the hydraulic gradient for different magnitudes of SLR. The general form of the equation for hydraulic gradient is:

$$
G = \frac{H_1 - H_2}{L}
$$

Let's use values of SLR ranging from 0 to 2 meters: `[0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2]`

In [6]:
# Make an array defining our SLR values

SLRs = [0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2]

df_tampa = pd.DataFrame(SLRs, columns = ['SLR'])
df_seattle = df_tampa.copy()

In [7]:
# Let's make a function to calculate this.
def calc_G(H1, H2, L):
    G = (H1 - H2) / L
    return G

In [11]:
Gs_tampa = []
Gs_seattle = []

H_tampa = data.loc['Tampa']['H_well']
H_seattle = data.loc['Seattle']['H_well']
L = data.loc['Tampa']['distance']

for SLR in SLRs:
    G_tampa = calc_G(H_tampa, SLR, L)
    G_seattle = calc_G(H_seattle, SLR, L)
    Gs_tampa.append(G_tampa)
    Gs_seattle.append(G_seattle)

df_tampa['G'] = Gs_tampa
df_seattle['G'] = Gs_seattle

## 7.3 - Wedge Shape Calculation
To calculate the shape of the salt water wedge ($a$), we can use a simple equation that depends on salt water's specific gravity ($s$), the depth of the aquifer ($d$), the hydrolic gradient ($G$), and the depth of the aquifer below sea-levl ($b$):
$$
a = \frac{s(s-1)d^2}{2Gb}
$$

In [8]:
# Let's make a function to calculate this. 
def calc_a(d, G, b, s=spec_grav):
    a = (s * (s-1) * d**2) / (2*G*b)
    return a

In [13]:
# Now, let's make a for loop to calculate the shape of each wedge for a given sea-level rise magnitude
as_tampa = []
as_seattle = []
d_tampa = data.loc['Tampa']['depth_d']
b_tampa = data.loc['Tampa']['depth_b']

d_seattle = data.loc['Seattle']['depth_d']
b_seattle = data.loc['Seattle']['depth_b']

for i in range(len(SLRs)):
    G_tampa = df_tampa['G'][i]
    a_tampa = calc_a(d_tampa, G_tampa, b_tampa)
    as_tampa.append(a_tampa)

    G_seattle = df_seattle['G'][i]
    a_seattle = calc_a(d_seattle, G_seattle, b_seattle)
    as_seattle.append(a_seattle)

df_tampa['a'] = as_tampa
df_seattle['a'] = as_seattle

    SLR         G           a
0  0.00  0.010000  359.800000
1  0.25  0.009975  360.701754
2  0.50  0.009950  361.608040
3  0.75  0.009925  362.518892
4  1.00  0.009900  363.434343
5  1.25  0.009875  364.354430
6  1.50  0.009850  365.279188
7  1.75  0.009825  366.208651
8  2.00  0.009800  367.142857

In [15]:
# Percent Difference

def calc_per_diff(a1, a2):
    diff = (a2 - a1) / a1
    return diff * 100

In [16]:
a1_tampa = df_tampa['a'][0]
a1_seattle = df_seattle['a'][0]

diffs_tampa = []
diffs_seattle = []

for i in range(len(df_tampa['a'])):
    diff_tampa = calc_per_diff(a1_tampa, df_tampa['a'][i])
    diffs_tampa.append(diff_tampa)
    
    diff_seattle = calc_per_diff(a1_seattle, df_seattle['a'][i])
    diffs_seattle.append(diff_seattle)

df_tampa['per_diff'] = diffs_tampa
df_seattle['per_diff'] = diffs_seattle

    SLR         G            a   per_diff
0  0.00  0.000500  1439.200000   0.000000
1  0.25  0.000475  1514.947368   5.263158
2  0.50  0.000450  1599.111111  11.111111
3  0.75  0.000425  1693.176471  17.647059
4  1.00  0.000400  1799.000000  25.000000
5  1.25  0.000375  1918.933333  33.333333
6  1.50  0.000350  2056.000000  42.857143
7  1.75  0.000325  2214.153846  53.846154
8  2.00  0.000300  2398.666667  66.666667

For this lab's deliverable, submit a word document with answers to these questions:
1. How does the position of the saltwater wedge toe vary with varying sea level rise (0 to 2 m)? Why?

In addition, you will submit a plot for each of the following sections and answer a corresponding question (provided below).

## 7.4 - Sensitivity Analysis

We will examine the impact of changing different parameters on the salt water intrusion. We'll use a reference aquifer with parameters defined below.

In [ ]:
H_coast = 0
H_well = 5
L = 10000
depth_b = 30
depth_d = 30
hyd_cond = 1.6e-5
spec_grav = 1.025

### 7.4.1 - Sensitivity to Hydraulic Head

In [ ]:
H_heads = np.arange(5,105, 5)

In [ ]:
# Plot of sensitivity to Hydraulic Head

2. How sensitive is the position of the saltwater toe to sea level rise? Under what aquifer parameters is an aquifer most sensitive to sea level rise?

### 7.4.2 - Sensitivity to Aquifer Depth

In [ ]:
depths = np.arange(10, 210, 10)

In [ ]:
# Plot of sensitivity to aquifer depth

3. How sensitive is the position of the saltwater toe to sea level rise? Under what aquifer parameters is an aquifer most sensitive to sea level rise?

### 7.4.3 - Sensitivity to Salt Water Density

In [ ]:
spec_gravs = np.arange(1.02, 1.031, 0.001)

In [17]:
# Plot of sensitivity to salt water density

4. How sensitive is the position of the saltwater toe to sea level rise? Under what aquifer parameters is an aquifer most sensitive to sea level rise?